### ISSUE TITLE
StructuredText Vue slot warnings

### ISSUE THREAD

**Issue by gavin667** [datocms/vue-datocms#104]
The below rule renders `[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance. `

<img width="820" alt="Screenshot 2024-12-05 at 11 36 11" src="https://github.com/user-attachments/assets/b63ebd62-7542-4a8b-9b6b-2a4a5d32ecbf">

```
        renderRule(
          isLink,
          ({ adapter: { renderNode: h }, node, children, key }) => {
            return h(
              VisionLink,
              {
                key,
                lineLink: true,
                size: 'inherit',
                to: this.resolveLocalePath(node.url),
                display: 'inline-block',
              },
              children
            )
          }
        ),
```

If I pass children as function, like so:

```
        renderRule(
          isLink,
          ({ adapter: { renderNode: h }, node, children, key }) => {
            return h(
              VisionLink,
              {
                key,
                lineLink: true,
                size: 'inherit',
                to: this.resolveLocalePath(node.url),
                display: 'inline-block',
              },
              () => children
            )
          }
        ),
```

It just outputs the function text:

<img width="642" alt="Screenshot 2024-12-05 at 11 34 07" src="https://github.com/user-attachments/assets/19c23d6e-9661-4aac-99f4-8185e497b51b">

Looking at the [Vue docs](https://vuejs.org/api/render-function#h) for the `h` render function, I should be able to do:

```
        renderRule(
          isLink,
          ({ adapter: { renderNode: h }, node, children, key }) => {
            return h(
              VisionLink,
              {
                key,
                lineLink: true,
                size: 'inherit',
                to: this.resolveLocalePath(node.url),
                display: 'inline-block',
              },
              {
                default: () => children
              }
            )
          }
        ),
```

But now I get:

<img width="634" alt="Screenshot 2024-12-05 at 11 36 59" src="https://github.com/user-attachments/assets/9586a5e4-260d-4af4-a77f-768b3fa57b83">

The `VisionLink` component has a single slot:

<img width="412" alt="Screenshot 2024-12-05 at 11 45 17" src="https://github.com/user-attachments/assets/a853b302-a531-42a9-877f-fc7350974e89">

What is the correct way to fix this warning? With later versions of Nuxt warning messages are becoming more prominent in the logs so fixing this is becoming more of a priority?

Any help is greatly appreciated. Thanks!

**Comment by stefanoverna** [comment]
This is exactly what we're doing in [our starter](https://github.com/datocms/nuxt-starter-kit/blob/main/pages/index.vue#L61-L63)... you can deploy it by pressing the "Start free project" CTA.

As you can see, we're using a function, and the content of the slot is correctly outputted.. I we remove the function, we're getting the warning.

I'm not really sure what's happening in your case. Are you able to share some small example reproducing the issue, so we can investigate? :/

**Comment by gavin667** [comment]
Hi @stefanoverna thanks for the link to the starter kit, that proved to be useful. We've now gotten to the bottom of this and it seems it was our use use of `adapter: { renderNode: h }` that was causing this to throw the warning. Removing it resolves the warning and renders the content correctly 🎉 

### Before
```
  renderRule(
          isLink,
          ({ adapter: { renderNode: h }, node, children, key }) => {
            return h(
              VisionLink,
              {
                key,
                lineLink: true,
                size: 'inherit',
                to: this.resolveLocalePath(node.url),
                display: 'inline-block',
              },
              () => children
            )
          }
  ),
```

### After
```
  renderRule(
          isLink,
          ({ node, children, key }) => {
            return h(
              VisionLink,
              {
                key,
                lineLink: true,
                size: 'inherit',
                to: this.resolveLocalePath(node.url),
                display: 'inline-block',
              },
              () => children
            )
          }
  ),
```

Thanks for your help and apologies for the noise. Hopefully SEO might prevail here and  help someone else in the future!

**Comment by stefanoverna** [comment]
Don't apologize! It's not normal that `adapter: { renderNode: h }` behaves differently from `h`! v7.0.6 should fix the issue. Thanks for reporting!
