### ISSUE TITLE
Wrap structured text without blocks

### ISSUE THREAD

**Issue by gilesbutler** [datocms/vue-datocms#29]
Hi Dato Team,

Congrats on the structured text release, it's absolutely awesome and changing the game for how we build sites 👏

One issue we've noticed is that it's not possible to wrap text output from the Vue `<datocms-structured-text />` component in a div tag without wrapping nested blocks as well. This really limits some designs as it's tricky to target the text content without inadvertently effecting nested blocks. For instance, take the following markup coming back from a structured text field in Dato...
```
<h1>Some Title</h1>
<p>Habitant et porta enim cubilia sem nisl</p>
<ul>
    <li>A list item</li>
</ul>

<div class="custom-block">A Custom Block</div>

<p>Habitant et porta enim cubilia sem nisl mi tellus</p>
```
Say you want to have just the text content at a certain width for legibility i.e 600px. But your custom block is a form that needs to be 100% width. If you wrap everything in a div that is 600px your form will be constrained to that width. It would be great to be able to do something like the following...
```
<div class="some-custom-class">
    <h1>Some Title</h1>
    <p>Habitant et porta enim cubilia sem nisl</p>
    <ul>
        <li>A list item</li>
    </ul>
</div>

<div class="custom-block">A Custom Block</div>

<div class="some-custom-class">
    <p>Habitant et porta enim cubilia sem nisl mi tellus</p>
</div>
```
That way you could easily target your text content and style it separately to your custom blocks. 

I tried to get this working with the `customRules` prop and `renderRule` but I could only wrap every tag with a `div` which isn't ideal or semantic. Maybe I'm doing it wrong?
```
customRules: [
        renderRule(
          isParagraph,
          ({ adapter: { renderNode }, node, children, key }) => {
            return (
              <div class="mx-auto prose">
                {renderNode(`p`, { key }, children)}
              </div>
            );
          }
        ),
        renderRule(
          isHeading,
          ({ adapter: { renderNode }, node, children, key }) => {
            return (
              <div class="mx-auto prose">
                {renderNode(`h${node.level + 1}`, { key }, children)}
              </div>
            );
          }
        ),
        renderRule(
          isList,
          ({ adapter: { renderNode }, node, children, key }) => {
            return (
              <div class="mx-auto prose">
                {renderNode(`ul`, { key }, children)}
              </div>
            );
          }
        ),
...
```

I hope that all makes sense but happy to discuss more and help in anyway I can.

Thanks

Giles

**Comment by stefanoverna** [comment]
Hi @gilesbutler!
I think the best way, until we might come up with some specific option for this, is to tweak the structured text tree, wrapping every children of the root node that's not a block in a new, custom, non-standard `group` node:

```js
import { isBlock } from 'datocms-structured-text-utils';

structuredText.value.document.children = structuredText.value.document.children.reduce((newChildren, node) => {
  if (isBlock(node)) {
    return [...newChildren, node];
  }

  const lastNode = newChildren.length > 0 && newChildren[newChildren.length - 1];

  if (lastNode && lastNode.type === 'group') {
    lastNode.children.push(node);
    return newChildren;
  }

  return [...newChildren, { type: 'group', children: [node] }];
}, []);
```

And then adding a custom render rule for group nodes:

```js
customRules: [
  renderRule(
    (node) => node.type === 'group',
    ({ adapter: { renderNode }, children, key }) => {
      return renderNode("div", { key, class: 'some-custom-class' }, children);
    },
  ),
],
```

**Comment by gilesbutler** [comment]
Thanks @stefanoverna that worked well and is a much cleaner solution. 

Really appreciate the fast response 👍

**Comment by gilesbutler** [comment]
Hey @stefanoverna,

The code above works well on most pages but sometimes we're getting the following JS error...

````
Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild
````

If I remove the code which creates the group above then the error goes away. Any idea what could be causing the error? 

Thanks

**Comment by stefanoverna** [comment]
would be helpful if you could paste the Structured Text value that triggers this error @gilesbutler

**Comment by gilesbutler** [comment]
Thanks for getting back to me @stefanoverna 

Here's some of the content we're passing in...

````
{"blocks":[{"id":"29090382","itemType":"video_block","youtubeId":"pq6XxCB2xQQ","imageHref":"","image":null}],"value":{"schema":"dast","document":{"type":"root","children":[{"type":"paragraph","level":null,"item":"","children":[{"type":"span","value":"In this chat, ","url":"","marks":[],"children":[]},{"type":"link","value":"","url":"https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fstaffordhamilton%2F&data=04%7C01%7Cblenda.eltz%40maiafinancial.com.au%7Cd8a151b498ed40648c0b08d89bbfb901%7C8e019ac9552b4cd591f4405c12a9e8f3%7C0%7C0%7C637430595153506695%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tgKWUTHU3X2bpLFcFKZ3zYW0jXyi7AEl3U4y5e1hrxw%3D&reserved=0","marks":[],"children":[{"type":"span","value":"Stafford Hamilton","marks":[]}]},{"type":"span","value":" (CEO, Credabl) and ","url":"","marks":[],"children":[]},{"type":"link","value":"","url":"https://www.linkedin.com/in/kelly-gall-21513826/","marks":[],"children":[{"type":"span","value":"Kelly Gall","marks":[]}]},{"type":"span","value":" (Finance Specialist, Credabl) discuss the benefits of choosing Buy Now Pay Later as a finance option for your practice equipment and technology.","url":"","marks":[],"children":[]}]},{"type":"paragraph","level":null,"item":"","children":[{"type":"span","value":"If you’re considering purchasing equipment, listen to what Stafford and Kelly have to say about Buy Now Pay Later as an option.","url":"","marks":[],"children":[]}]},{"type":"block","level":null,"item":"29090382","children":[]},{"type":"paragraph","level":null,"item":"","children":[{"type":"span","value":"Follow us on ","url":"","marks":[],"children":[]},{"type":"link","value":"","url":"https://www.instagram.com/credabl/?hl=en","marks":[],"children":[{"type":"span","value":"Instagram","marks":[]}]},{"type":"span","value":", ","url":"","marks":[],"children":[]},{"type":"link","value":"","url":"https://www.facebook.com/credabl/","marks":[],"children":[{"type":"span","value":"Facebook","marks":[]}]},{"type":"span","value":" or ","url":"","marks":[],"children":[]},{"type":"link","value":"","url":"https://www.linkedin.com/company/credabl/","marks":[],"children":[{"type":"span","value":"LinkedIn","marks":[]}]},{"type":"span","value":" so you can register for our upcoming webinars covering a whole range of topics.","url":"","marks":[],"children":[]}]},{"type":"paragraph","level":null,"item":"","children":[{"type":"link","value":"","url":"https://www.credabl.com.au/subscribe/","marks":[],"children":[{"type":"span","value":"Sign up","marks":[]}]},{"type":"span","value":" to hear about our next webinar.","url":"","marks":[],"children":[]}]}]}}}
````

From what I've read online, the error we're getting is usually related to hydration issues. We're using Gridsome and the [gridsome-dato plugin](https://gridsome.org/plugins/@gridsome/source-datocms) to pull in the content from Dato. We then pass the structured text content to a `groupStrutcturedTextContent` function. This is basically the code you provided with some fail safes built in.

````
const groupStrutcturedTextContent = (data = {}) => {
  // Custom renderRule used to wrap Dato text content separate to blocks - see https://github.com/datocms/vue-datocms/issues/29
  const content = Object.assign({}, data);

  if (get(content, "value.document.children")) {
    content.value.document.children = content.value.document.children.reduce(
      (newChildren, node) => {
        if (isBlock(node)) {
          return [...newChildren, node];
        }

        const lastNode =
          newChildren.length > 0 && newChildren[newChildren.length - 1];

        console.log("lastNode", lastNode);

        if (lastNode && lastNode.type === "group") {
          lastNode.children.push(node);
          return [lastNode];
          // return newChildren;
          // return [...newChildren, lastNode];
        }
        return [...newChildren, { type: "group", children: [node] }];
      },
      []
    );
  }

  return content;
};
````

Which is run in the vue created hook and assigned to a reactive data prop...
````
  created() {
    this.article = this.$get(this, "$page.article");

    this.articleContent = groupStrutcturedTextContent(
      this.$get(this, "article.content")
    );
  },
````

And then passed to the component...
```
<DatocmsStructuredText
    :data="articleContent"
    :renderBlock="renderDefaultBlocks"
    :customRules="structuredTextCustomRules"
/>
```

We do it this way to make `groupStrutcturedTextContent` reusable across different components. The customRules are also imported from a setup file as they need to be reused across multiple components too.

We were also wondering what `lastNode.children.push(node);` in your example code as it seems redundant?
```
if (lastNode && lastNode.type === "group") {
  lastNode.children.push(node);
  return newChildren;
}
``` 

Hope that gives a bit more context

Thanks

**Comment by stefanoverna** [comment]
Your `groupStrutcturedTextContent` does not throw any error with the structured text you provided in my test. Also, the way you changed it breaks its behaviour:

```js
[...]

// the current node is not a block, so we want to wrap it in a "group" node!

// is the last children of root node a group already?
if (lastNode && lastNode.type === "group") {
  // if so, add the current node as its children
  lastNode.children.push(node);
  // and since we're in a `reduce` function, return the current accumulator with no 
  // changes (that is, we're removing the current node from the new root children list)
  return newChildren;
}

// if there's no "group" node, create a new one, add the current node as it's 
// children and return the new root children list with the new group node! 
return [...newChildren, { type: 'group', children: [node] }];
```

**Comment by gilesbutler** [comment]
Hi @stefanoverna,

> Also, the way you changed it breaks its behaviour:

Please can you explain how and where exactly so I can fix?

Where should the following be added for this to work? 
`structuredText.value.document.children = structuredText.value.document.children.reduce((newChildren, node) => ...`
In a computed property? In a method? In the created hook?

Gridsome pulls in the content at build time and adds it the component as a reactive prop under something like `this.$page.customPage` the the structured text content is at `this.$page.customPage.content`.

Thanks

**Comment by gilesbutler** [comment]
I tried the following in a computed property and I still get the same error when I build for production...
```
content() {
      this.$page.customPage.content.value.document.children = this.$page.customPage.content.value.document.children.reduce(
        (newChildren, node) => {
          if (isBlock(node)) {
            return [...newChildren, node];
          }

          const lastNode =
            newChildren.length > 0 && newChildren[newChildren.length - 1];

          if (lastNode && lastNode.type === "group") {
            lastNode.children.push(node);
            return newChildren;
          }

          return [...newChildren, { type: "group", children: [node] }];
        },
        []
      );

      return this.$page.customPage.content;
    },
```

How are you testing the content on your end? This issue only happens when we build for production and not in development.

Thanks

**Comment by stefanoverna** [comment]
Thanks for the feedback! Are you able of sharing the repo of your project? I've tested it without reactive props in a basic scaffolded vue project, didn't know you were using Gridsome

--- original message ---
On Fri, Apr 23 at 07:03 AM, ***@***.***> Giles Butler wrote:



I tried the following in a computed property and I still get the same error when I build for production...

content() {
this.$page.customPage.content.value.document.children = this.$page.customPage.content.value.document.children.reduce(
(newChildren, node) => {
if (isBlock(node)) {
return [...newChildren, node];
}

const lastNode =
newChildren.length > 0 && newChildren[newChildren.length - 1];

if (lastNode && lastNode.type === "group") {
lastNode.children.push(node);
return newChildren;
}

return [...newChildren, { type: "group", children: [node] }];
},
[]
);

return this.$page.customPage.content;
},

How are you testing the content on your end? This issue only happens when we build for production and not in development.

Thanks

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by gilesbutler** [comment]
I wish I could share the repo but unfortunately it's a client project and they won't allow it.

I've just tested by using the same setup in your example i.e using Axios in the created hook to query dato and it works, no error anymore!

Unfortunately we lose out on the server side rendering plus we have to restructure a bunch of queries to get this working as the queries that work in the Dato API explorer don't work in the gridsome query. Also I'm not sure how it will work for dynamic pages like blog articles, I assume I'll have to pass the url/slug into the query. 

I guess this is an issue with the gridsome-dato plugin as it hasn't been updated in at least 6 months so it might need some work to get it to work with structured text.

**Comment by gilesbutler** [comment]
Actually I'm not sure it is an issue with the gridsome-dato plugin @stefanoverna. When I revert back to the original code and remove the custom grouping code then run a build I don't get any errors. It seems as though something in the custom grouping code is causing the error but only when build for production. Whenever we build for production and gridsome does it's server side rendering Vue isn't happy with the markup that it's getting back from the custom group by the looks of it.

**Comment by stefanoverna** [comment]
This is a fully working gridsome example @gilesbutler... the datocms source plugin does not work for me (we're not the ones who maintain it), but I've uses the graphql source plugin, which is more than fine.

Example: https://github.com/stefanoverna/gridsome-test/blob/main/src/pages/Index.vue

Both develop and build work as expected.

![Screenshot 2021-04-23 at 15 40 49](https://user-images.githubusercontent.com/51573/115879743-4b223400-a44a-11eb-97af-4094dc378fba.png)

I'm sorry, but there's not much else I can do about this issue unless you can give me a repository that reproduces the problem 😞

**Comment by gilesbutler** [comment]
Hi @stefanoverna thanks so much for the above, really appreciate you taking the time to create a gridsome test. I think this boils down to the gridsome-source-dato plugin. Unfortunately we need to use the dato plugin as the graphql-source plugin is actually very different to all the other source plugins out there see https://github.com/gridsome/gridsome/issues/870 - When it comes to creating pages/templates the dato plugin does all the heavy lifting and we've built the whole site on it. Go live is tomorrow so a bit too late to change at this stage.

Your repo really helped though as I'd forgotten about the graphql source plugin. I've done a bit of a spike and I'm testing using both plugins at the same time. It's not ideal but I'm trying to use the graphql source plugin to just pull in the structured text content for the 2 models we use it on. The dato source plugin then does all the other content. I'll see how I go with that setup 🤞

Thanks again, really appreciate your help 👍
