### ISSUE TITLE
Image component - optional Easing propoerty for transition

### ISSUE THREAD

**Issue by MartCube** [datocms/vue-datocms#38]
Hello there, first I just wanna praise you for your good work. :+1: 
I was using your image component and Its working great.
I was just wondering can we add a property to tweak the easing of the image transition.
we have similar property for the duration of the transition.

**Comment by stefanoverna** [comment]
Thanks @MartCube! PR are welcome, do you think you can find some time to work on this?

**Comment by MartCube** [comment]
I will try to fork and work on this, thanks @stefanoverna
