### ISSUE TITLE
Vue2 crashes on StructureText

### ISSUE THREAD

**Issue by falko-apheris** [datocms/vue-datocms#58]
I am using Nuxt and Vuetify which are both not production ready in Vue3. Therefor I need a support for Vue2.

While the documentation states that 
> If you want to use this package with Vue 2, please, install vue-datocms@1
I tried working with a `1.x` version but that is not possible

```
npm ERR! While resolving: x@1.0.0
npm ERR! Found: vue-datocms@0.2.5
npm ERR! node_modules/vue-datocms
npm ERR!   vue-datocms@"1.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! vue-datocms@"1.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.0
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.0.0-rc.1" from vue-datocms@1.1.0
npm ERR!     node_modules/vue-datocms
npm ERR!       vue-datocms@"1.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
``` 
Therfore I used the latest version before 1: [0.2.5](https://www.npmjs.com/package/vue-datocms/v/0.2.5)

This worked for the most part but the `StructuredText` Component fails to render. The build already returns a warning
```
 WARN  in ./node_modules/vue-datocms/dist/vue-datocms.esm.js     friendly-errors 16:49:47

"export 'renderRule' was not found in 'datocms-structured-text-generic-html-renderer'
```
Which I figured out is due to a renaming of `renderRule` to `renderNodeRule` however even changing that in the sources results in further error.

I kindly ask you to show me a path on how to proceed with production ready version of Vue and your library.

**Comment by matjack1** [comment]
hello @falko-apheris sorry for the delay on this. Meanwhile we have released a new version of vue-datocms and this might be outdated. I'm going to close now, but please reopen if still relevant
