### ISSUE TITLE
Can't render components through renderBlock function

### ISSUE THREAD

**Issue by enrico-bagattin** [datocms/vue-datocms#60]
Hi, I'm building a blog with DatoCMS and Nuxt3 (Vue 3), the problem is when I try to render custom blocks inside structured text.
My renderBlock function is the same as the one in the examples:

```
renderBlock: ({ record }) => {
      switch (record.__typename) {
        case 'ImageRecord':
          return h('datocms-image', {
            data: record.image.responsiveImage,
          });
        default:
          return null;
      }
    },
```

If I place the datocms-image component directly in the template for the article cover it works well, but inside the structured data is not rendered and inspecting the DOM I found this `<datocms-image data="[object Object]"></datocms-image>`.

I have tried also with another block type and a custom component and the result is the same even with no parameters.

Is there some documentation for this function?

**Comment by enrico-bagattin** [comment]
I found how to solve this in the Vue3 doc: https://vuejs.org/guide/extras/render-function.html#components

**Comment by stefanoverna** [comment]
great! could you please share the correct snippet here as well? thanks!

**Comment by enrico-bagattin** [comment]
Here it is
```
renderBlock({record, key}) {
      switch (record.__typename) {
        case 'ImageRecord':
          return h(Image, {data: record.image.responsiveImage} );
        default:
          return null;
      }
    },
```
easier than expected!
